#!/usr/bin/env node

import { readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const GAME_DIR = join(__dirname, '..', '..', '..');
const TRANS_FILE = join(GAME_DIR, 'BepInEx', 'Translation', 'ru', 'Text', '_AutoGeneratedTranslations.txt');

const args = process.argv.slice(2);
const DRY_RUN = args.includes('--dry-run');

async function loadExisting() {
    const map = new Map();
    try {
        const content = await readFile(TRANS_FILE, 'utf-8');
        for (const line of content.split('\n')) {
            const eq = line.indexOf('=');
            if (eq > 0) map.set(line.slice(0, eq), line.slice(eq + 1));
        }
    } catch { /* file may not exist */ }
    return map;
}

async function translateBatch(texts) {
    if (!texts.length) return [];
    const payload = JSON.stringify([[texts.map(t => [t, 'en', 'ru', 1]), 'wt_lib']]);
    try {
        const res = await fetch('https://translate.googleapis.com/translate_a/t', {
            method: 'POST',
            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
            body: new URLSearchParams({ 'f.req': payload })
        });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data = await res.json();
        return data[0][0].map(r => r[0][0][5]?.[0]?.[0] || '');
    } catch (err) {
        console.error(`  Ошибка: ${err.message}`);
        return texts.map(() => null);
    }
}

async function main() {
    console.log('=== Пакетный перевод ===\n' + (DRY_RUN ? '* DRY RUN *\n' : ''));
    const existing = await loadExisting();
    console.log(`Существующих: ${existing.size}`);

    let toTranslate = [];
    const srcIdx = args.indexOf('--source');
    if (srcIdx >= 0 && args[srcIdx + 1]) {
        const c = await readFile(args[srcIdx + 1], 'utf-8');
        toTranslate = c.split('\n').filter(l => l.trim()).map(l => l.replace(/=$/, ''));
    } else {
        for (const [orig, trans] of existing)
            if (orig === trans && orig.length > 3) toTranslate.push(orig);
    }

    toTranslate = toTranslate.filter(t => {
        const ex = existing.get(t);
        return !ex || ex === t || !ex.length;
    });

    console.log(`Требуют перевода: ${toTranslate.length}`);
    if (!toTranslate.length) { console.log('Нечего переводить.'); return; }

    const BATCH = 25;
    let done = 0, failed = 0;

    for (let i = 0; i < toTranslate.length; i += BATCH) {
        const batch = toTranslate.slice(i, i + BATCH);
        console.log(`Пакет ${Math.floor(i / BATCH) + 1}/${Math.ceil(toTranslate.length / BATCH)} (${batch.length})...`);

        if (!DRY_RUN) {
            const results = await translateBatch(batch);
            for (let j = 0; j < results.length; j++) {
                if (results[j]) { existing.set(batch[j], results[j]); done++; }
                else failed++;
            }
            const lines = [...existing].map(([o, t]) => `${o}=${t}`);
            await writeFile(TRANS_FILE, lines.join('\n'), 'utf-8');
        }
        if (i + BATCH < toTranslate.length) await new Promise(r => setTimeout(r, 1000));
    }

    if (DRY_RUN) console.log(`Будет переведено: ${toTranslate.length}`);
    else console.log(`\nГотово! Переведено: ${done}, Ошибок: ${failed}`);
}

main().catch(console.error);
