#!/usr/bin/env node

import { readFile, readdir, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const GAME_DIR = join(__dirname, '..', '..', '..');
const TRANS_DIR = join(GAME_DIR, 'BepInEx', 'Translation', 'ru', 'Text');
const EN_DIR = join(GAME_DIR, 'BepInEx', 'Translation', 'en', 'Text');

async function analyzeMain() {
    console.log('=== Анализ файлов перевода ===\n');
    const path = join(TRANS_DIR, '_AutoGeneratedTranslations.txt');
    const content = await readFile(path, 'utf-8');
    const lines = content.split('\n').filter(l => l.trim() && l.includes('='));

    let good = 0, bad = 0, untranslated = 0;
    const problems = [];

    for (const line of lines) {
        const eq = line.indexOf('=');
        if (eq <= 0) { bad++; problems.push({ line, issue: 'Нет =' }); continue; }
        const orig = line.slice(0, eq);
        const trans = line.slice(eq + 1);
        if (!orig.trim()) { bad++; problems.push({ line, issue: 'Пустой оригинал' }); continue; }
        if (!trans.trim()) { bad++; problems.push({ line, issue: 'Пустой перевод' }); continue; }
        if (orig === trans && orig.length > 3) { untranslated++; problems.push({ line, issue: 'Непереведено' }); }
        good++;
    }

    console.log(`Всего: ${lines.length}, OK: ${good}, Проблем: ${bad}, Непереведено: ${untranslated}`);
    if (problems.length) {
        console.log('\n--- Проблемные (первые 15) ---');
        for (const p of problems.slice(0, 15)) console.log(`  [${p.issue}] ${p.line.slice(0, 100)}`);
    }

    const lens = lines.map(l => l.indexOf('=') > 0 ? l.slice(0, l.indexOf('=')).length : 0);
    console.log(`\nДлина оригинала: средняя ${(lens.reduce((a, b) => a + b, 0) / lens.length).toFixed(1)}, макс ${Math.max(...lens)}, мин ${Math.min(...lens)}`);
}

async function analyzeFiles() {
    console.log('\n=== Файлы в ru/Text/ ===');
    for (const f of await readdir(TRANS_DIR)) {
        const c = await readFile(join(TRANS_DIR, f), 'utf-8');
        console.log(`  ${f}: ${c.length} байт, ${c.split('\n').length} строк`);
    }
}

async function compareWithEn() {
    console.log('\n=== Сравнение с en-кэшем ===');
    try {
        const en = await readFile(join(EN_DIR, '_AutoGeneratedTranslations.txt'), 'utf-8');
        const ru = await readFile(join(TRANS_DIR, '_AutoGeneratedTranslations.txt'), 'utf-8');
        const enLines = new Set(en.split('\n').filter(l => l.includes('=')).map(l => l.split('=')[0]));
        const ruLines = new Set(ru.split('\n').filter(l => l.includes('=')).map(l => l.split('=')[0]));
        const missing = [...enLines].filter(e => !ruLines.has(e));
        console.log(`В en кэше: ${enLines.size}, в ru: ${ruLines.size}, не переведено: ${missing.length}`);
        if (missing.length) console.log('Примеры:', missing.slice(0, 10));
    } catch { console.log('Нет en-кэша'); }
}

analyzeMain().then(analyzeFiles).then(compareWithEn);
